/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package conversor;

import java.text.DecimalFormat;
import javax.swing.SwingConstants;

/**
 *
 * @author Andressa Marques
 */
public class TempTela extends javax.swing.JFrame {

    /**
     * Creates new form TempTela
     */
    public TempTela() {
        initComponents();
        lblResultado.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        cbGrau = new javax.swing.JComboBox<>();
        lblDescrição = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtValor = new javax.swing.JTextArea();
        tbmConverter = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Conversor de Temperaturas");

        cbGrau.setBackground(new java.awt.Color(255, 153, 153));
        cbGrau.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        cbGrau.setForeground(new java.awt.Color(255, 255, 255));
        cbGrau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius para Fahrenheit", "Celsius para Kelvin", "Fahrenheit para Celsius", "Fahrenheit para Kelvin", "Kelvin para Fahrenheit", "Kelvin para Celsius" }));
        cbGrau.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblDescrição.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblDescrição.setForeground(new java.awt.Color(0, 0, 0));
        lblDescrição.setText("Insira o valor:");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtValor.setBackground(new java.awt.Color(255, 204, 204));
        txtValor.setColumns(20);
        txtValor.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txtValor.setRows(5);
        txtValor.setAutoscrolls(false);
        txtValor.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(txtValor);

        tbmConverter.setBackground(new java.awt.Color(255, 153, 153));
        tbmConverter.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        tbmConverter.setForeground(new java.awt.Color(255, 255, 255));
        tbmConverter.setText("Converter");
        tbmConverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbmConverterActionPerformed(evt);
            }
        });

        lblResultado.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lblResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultado.setText("Resultado");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/download(1).jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(tbmConverter, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbGrau, 0, 194, Short.MAX_VALUE)
                                    .addComponent(lblResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDescrição)
                                .addGap(44, 44, 44)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblTitulo)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescrição))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbGrau, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(tbmConverter, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbmConverterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbmConverterActionPerformed
        
        ConversorTemp ct = new ConversorTemp();
        DecimalFormat df = new DecimalFormat("0.00");
        String input = cbGrau.getSelectedItem().toString();
        double valor = Double.parseDouble(txtValor.getText());
        
        switch(input){
            
            case "Celsius para Fahrenheit":
                ct.celParaFah(valor);
                lblResultado.setVisible(true); 
                String res = df.format(ct.temp) + " ºF"; 
                lblResultado.setText(res);
                break;
                
            case "Celsius para Kelvin":
                ct.celParaKel(valor);
                lblResultado.setVisible(true); 
                String res1 = df.format(ct.temp) + " K"; 
                lblResultado.setText(res1);                
                break;
                
            case "Fahrenheit para Celsius":
                ct.fahParaCel(valor);
                lblResultado.setVisible(true); 
                String res2 = df.format(ct.temp) + " ºC"; 
                lblResultado.setText(res2);                
                break;
                
            case "Fahrenheit para Kelvin":
                ct.fahParaKel(valor);
                lblResultado.setVisible(true); 
                String res3 = df.format(ct.temp) + " K"; 
                lblResultado.setText(res3);                
                break;               
                
            case "Kelvin para Fahrenheit":
                ct.kelParaFah(valor);
                lblResultado.setVisible(true); 
                String res4 = df.format(ct.temp) + " ºF"; 
                lblResultado.setText(res4);                
                break;
                
            case "Kelvin para Celsius":
                ct.kelParaCel(valor);
                lblResultado.setVisible(true); 
                String res5 = df.format(ct.temp) + " ºC"; 
                lblResultado.setText(res5); 
                break;  

        }
        
        
        
    }//GEN-LAST:event_tbmConverterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TempTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TempTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TempTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TempTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TempTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbGrau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescrição;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JButton tbmConverter;
    private javax.swing.JTextArea txtValor;
    // End of variables declaration//GEN-END:variables
}
